//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiemKeNVL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryItem
    {
        public int Id { get; set; }
        public string SheetId { get; set; }
        public string SapCode { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Workshop { get; set; }
        public string Machine { get; set; }
        public decimal Quantity { get; set; }
        public int Tubes { get; set; }
        public string Note { get; set; }
    
        public virtual InventorySheet InventorySheet { get; set; }
    }
}
